- src/main/java/com/kdt/mappers/GenericMapper.java
> CS-11 지라 연동 테스트 / generic mapper 추가

- pom.xml
- src/main/java/com/kdt/config/SecurityConfig.java
- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/domain/entities/Member.java
- src/main/java/com/kdt/dto/MemberDTO.java
- src/main/java/com/kdt/mappers/GenericMapper.java
- src/main/java/com/kdt/mappers/MemberMapper.java
- src/main/java/com/kdt/repositories/MemberRepository.java
- src/main/java/com/kdt/security/SecurityUser.java
- src/main/java/com/kdt/services/MemberSecurityService.java
- src/main/java/com/kdt/services/MemberService.java
각종 패키지 만들었고 스프링 시큐리티 1차로 작성했습니다. (보완 필요)
> NG-51 pakages & spring security create

- src/main/java/com/kdt/config/SecurityConfig.java
- src/main/resources/application.properties
db 이름 localhost에서 원격 db로 변경했습니다.
> application properties update

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/domain/entities/Board.java
- src/main/java/com/kdt/dto/BoardDTO.java
- src/main/java/com/kdt/mappers/BoardMapper.java
- src/main/java/com/kdt/mappers/GenericMapper.java
- src/main/java/com/kdt/repositories/BoardRepository.java
- src/main/java/com/kdt/services/BoardService.java
- src/main/resources/application.properties
- 파일제외한 자유게시판 게시글 삽입 기능 1차 완료
- 게시판 관련 service, controller, mapper, dto, entity 생성
> NG-58 자유게시판 게시글 삽입 기능 ( 파일 제외 )

- src/main/java/com/kdt/controllers/EstateController.java
- src/main/java/com/kdt/dto/EstateDTO.java
매물 관리 임시 백엔드 생성
디버깅을 위해 post 받은 값을 syout으로 출력합니다
DB 관련 작업은 아직입니다
> NG-57 <임시 백엔드 생성>

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/controllers/ReplyController.java
- src/main/java/com/kdt/domain/entities/Reply.java
- src/main/java/com/kdt/dto/ReplyDTO.java
- src/main/java/com/kdt/mappers/ReplyMapper.java
- src/main/java/com/kdt/repositories/ReplyRepository.java
- src/main/java/com/kdt/services/BoardService.java
- src/main/java/com/kdt/services/ReplyService.java
- 댓글 관련 서비스, 컨트롤러 등 생성
- 댓글 삽입 기능 추가
> NG-62 댓글 삽입 기능

- src/main/java/com/kdt/config/SecurityConfig.java
- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/services/MemberService.java
> NG-26 signup update

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/controllers/ReplyController.java
- src/main/java/com/kdt/domain/entities/Board.java
- src/main/java/com/kdt/dto/BoardDTO.java
- src/main/java/com/kdt/repositories/ReplyRepository.java
- src/main/java/com/kdt/services/ReplyService.java
> NG-64 게시글 댓글 목록 불러오기

- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/repositories/MemberRepository.java
- src/main/java/com/kdt/services/MemberService.java
> NG-66 id duplcheck create

- src/main/java/com/kdt/services/MemberService.java
member service 에 test용 sysout 제거했습니다.
> sysout remove

- src/main/java/com/kdt/controllers/ReplyController.java
- src/main/java/com/kdt/repositories/BoardRepository.java
- src/main/java/com/kdt/services/ReplyService.java
> NG-64 댓글 삭제 기능

- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/openapi/AgentOpneApi.java
- src/main/java/com/kdt/services/MemberService.java
리액트에서 그랬는데 src/main/java/com/kdt/openapi/는 테스트해보기위해 넣었어요
MemberController,MemberService는 전체 목록을 불러오는 코드와 삭제기능을 넣었습니다.
> NG-55 회원관리 추가

- src/main/java/com/kdt/controllers/EstateController.java
- src/main/java/com/kdt/domain/entities/Estate.java
- src/main/java/com/kdt/domain/entities/EstateOption.java
- src/main/java/com/kdt/dto/EstateOptionDTO.java
- src/main/java/com/kdt/dto/EstateRequestDTO.java
- src/main/java/com/kdt/mappers/EstateMapper.java
- src/main/java/com/kdt/mappers/EstateOptionMapper.java
- src/main/java/com/kdt/repositories/EstateOptionRepository.java
- src/main/java/com/kdt/repositories/EstateRepository.java
- src/main/java/com/kdt/services/EstateService.java
매물과 매물 옵션 관련된 Mapper, Service, Entitiy, DTO, Repository 추가
매물과 옵션을 세션에 저장해두었다가 모든 입력을 마치면 service로 Insert
Insert하는 절차는 트랜잭션으로 이루어짐
> 매물 / 매물 옵션 Insert 기능 추가

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/domain/entities/Real_Estate_Agent.java
- src/main/java/com/kdt/dto/RealEstateAgentDTO.java
- src/main/java/com/kdt/mappers/AgentMapper.java
- src/main/java/com/kdt/repositories/AgentRepository.java
- src/main/java/com/kdt/services/AgentService.java
- src/main/java/com/kdt/services/MemberService.java
> NG-56 공인중개사 관리 added

- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/repositories/MemberRepository.java
- src/main/java/com/kdt/services/MemberService.java
클라이언트로부터 이메일을 받아 db에서 아이디를 뽑아 보내는 기능을 추가했습니다.
> 이메일로 아이디 불러오기

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/domain/entities/Real_Estate_Agent.java
- src/main/java/com/kdt/services/AgentService.java
> NG-84 공인중개사 수정

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/domain/entities/NewMember.java
- src/main/java/com/kdt/dto/NewMemberDTO.java
- src/main/java/com/kdt/mappers/NewMemberMapper.java
- src/main/java/com/kdt/openapi/AgentOpenApi.java
- src/main/java/com/kdt/repositories/NewMemberRepository.java
- src/main/java/com/kdt/services/NewMemberService.java
AgentOpenApi.java는 아직 테스트 중이고 NewMember가 붙는 파일들은 신규 등록 수를 구하기 위해 추가를 했습니다.
> NG-53 신규 등록 수 추가

- src/main/java/com/kdt/domain/entities/Real_Estate_Agent.java
- src/main/java/com/kdt/dto/RealEstateAgentDTO.java
> NG-84 공인중개사 table 수정

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/repositories/VisitorRepository.java
- src/main/java/com/kdt/services/NewMemberService.java
- src/main/java/com/kdt/services/VisitorService.java
신규회원수와 방문자수를 차트로 만들었습니다. 그리고 nivo를 install했습니다.
> NG-85 메인페이지 수정

- src/main/java/com/kdt/controllers/EstateController.java
- src/main/java/com/kdt/domain/entities/Estate.java
- src/main/java/com/kdt/domain/entities/EstateImage.java
- src/main/java/com/kdt/domain/entities/EstateOption.java
- src/main/java/com/kdt/domain/entities/Room.java
- src/main/java/com/kdt/dto/RoomDTO.java
- src/main/java/com/kdt/repositories/RoomRepository.java
- src/main/java/com/kdt/services/EstateService.java
> DB명 대문자로 변경

- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/repositories/MemberRepository.java
- src/main/java/com/kdt/services/MemberService.java
회원정보 불러오기 기능, 회원 탈퇴 기능 만들었습니다.
> NG-27 mypage & deleteMyInfo update

- src/main/java/com/kdt/config/WebConfig.java
- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/controllers/FilesController.java
- src/main/java/com/kdt/domain/entities/Board.java
- src/main/java/com/kdt/domain/entities/Files.java
- src/main/java/com/kdt/dto/BoardDTO.java
- src/main/java/com/kdt/dto/BoardUploadDTO.java
- src/main/java/com/kdt/dto/FilesDTO.java
- src/main/java/com/kdt/mappers/BoardMapper.java
- src/main/java/com/kdt/services/BoardService.java
- src/main/java/com/kdt/services/MemberService.java
> NG-70 WebConfig 추가 ( 파일 시도중 )

- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/dto/UpdateMemberDTO.java
- src/main/java/com/kdt/repositories/MemberRepository.java
- src/main/java/com/kdt/services/MemberService.java
> NG-91 updateMyInfo create

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/domain/entities/Files.java
- src/main/java/com/kdt/dto/FilesDTO.java
- src/main/java/com/kdt/services/BoardService.java
> NG-70 게시판 글 작성 기능 ( 파일 포함 )

- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/repositories/MemberRepository.java
- src/main/java/com/kdt/services/MemberService.java
> NG-93 changePw create

- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/repositories/MapRepository.java
- src/main/java/com/kdt/services/MapService.java
맵에 관련된 스프링 부트 파일들 추가 되었습니다.
아직까지 큰 기능은 없구요. 그냥 findAll만 추가했습니다.
> map update

- pom.xml
- src/main/java/com/kdt/config/MailConfig.java
- src/main/java/com/kdt/controllers/MailController.java
- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/repositories/MemberRepository.java
- src/main/java/com/kdt/services/MailService.java
- src/main/java/com/kdt/services/MemberService.java
비밀번호 찾기 기능이 추가되었습니다.
Spring Boot Starter Mail 을 추가하였습니다.
임시 코드로 비밀번호가 변경됩니다.
> findPw create

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/domain/entities/Real_Estate_Agent.java
- src/main/java/com/kdt/dto/RealEstateAgentDTO.java
- src/main/java/com/kdt/services/AgentService.java
entity와 dto는 속성 추가를 하였고 나머지는 insert가 되도록 메서드 추가 하였습니다.
> NG-108 공인중개사 등록

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/mappers/BoardMapper.java
- src/main/java/com/kdt/repositories/FileRepository.java
- src/main/java/com/kdt/services/BoardService.java
> NG-82 게시글 수정 기능

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/repositories/AgentRepository.java
- src/main/java/com/kdt/services/AgentService.java
> NG-108 공인중개사 등록 수정

- src/main/java/com/kdt/DaebangApplication.java
- src/main/java/com/kdt/config/SecurityConfig.java
관리자 로그인 만들고 스프링 시큐리티로 관리자 데이터 못넘어오게 막았습니다.
추가로 app.js에서 로그인 안할 시 마이페이지 이동 막았고, 관리자가 아닐 시 관리자 페이지 이동 막았습니다.
> NG-106 admin login create & spring security update

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/controllers/FavoriteBoardController.java
- src/main/java/com/kdt/domain/entities/Board.java
- src/main/java/com/kdt/domain/entities/FavoriteBoard.java
- src/main/java/com/kdt/dto/BoardDTO.java
- src/main/java/com/kdt/dto/FavoriteBoardDTO.java
- src/main/java/com/kdt/mappers/FavoriteBoardMapper.java
- src/main/java/com/kdt/repositories/BoardRepository.java
- src/main/java/com/kdt/repositories/FavoriteBoardRepository.java
- src/main/java/com/kdt/services/BoardService.java
- src/main/java/com/kdt/services/FavoriteBoardService.java
- 자유게시판 / 양도게시판 즐겨찾기 등록, 삭제
- 게시글 목록에 즐겨찾기 여부 함께 표시되는 기능
> NG-72 자유게시판 / 양도게시판 즐겨찾기 등록, 삭제

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/repositories/BoardRepository.java
- src/main/java/com/kdt/services/BoardService.java
> NG-72 즐겨찾기 기능

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/domain/entities/NewEstate.java
- src/main/java/com/kdt/dto/NewEstateDTO.java
- src/main/java/com/kdt/mappers/NewEstateMapper.java
- src/main/java/com/kdt/repositories/MemberRepository.java
- src/main/java/com/kdt/repositories/NewEstateRepository.java
- src/main/java/com/kdt/services/AgentService.java
- src/main/java/com/kdt/services/MemberService.java
- src/main/java/com/kdt/services/NewEstateService.java
- src/main/java/com/kdt/services/NewMemberService.java
새로 추가한 파일들은 신규 공인중개사 등록하면 관리자 메인페이지에서 차트로 보여줄 수 있게 테이블을 추가했습니다.
AdminController에서는 회원관리를 수정하였는데 role이 member인 사람만 보이게 수정을 하였습니다.
> NG-53 메인페이지 수정

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/repositories/NewEstateRepository.java
- src/main/java/com/kdt/repositories/NewMemberRepository.java
- src/main/java/com/kdt/services/NewEstateService.java
- src/main/java/com/kdt/services/NewMemberService.java
누적수와 오늘 등록수를 각각 회원과 공인중개사를 만들었습니다.
> NG-53 관리자 메인페이지 수정

- src/main/java/com/kdt/controllers/FilesController.java
> NG-92 게시글 파일 다운로드

- src/main/java/com/kdt/controllers/EstateController.java
- src/main/java/com/kdt/services/EstateService.java
매물과 연관된 테이블의 내용을 지우고
다시 생성후
매물은 업데이트하는 로직으로 행동
> 매물 정보 수정 기능

- src/main/java/com/kdt/DaebangApplication.java
- src/main/java/com/kdt/config/SecurityConfig.java
- src/main/java/com/kdt/services/AgentService.java
- src/main/java/com/kdt/services/EstateSecurityService.java
- src/test/java/com/kdt/DaebangApplicationTests.java
> NG-115 estate login create

- src/main/java/com/kdt/config/SecurityConfig.java
스프링 시큐리티 데이터 받아오는 권한 통제 코드 수정했습니다.
> NG-116 spring security right update

- src/main/java/com/kdt/controllers/EstateAgentController.java
- src/main/java/com/kdt/repositories/AgentRepository.java
- src/main/java/com/kdt/services/AgentService.java
공인중개사 마이페이지 정보 띄우기, 회원탈퇴, 비밀번호 변경 기능 완료했습니다.
> NG-118 estate mypage read&delete&pwupdate

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/controllers/Enrollmentcontroller.java
- src/main/java/com/kdt/controllers/VisitorController.java
- src/main/java/com/kdt/domain/entities/Real_Estate_Agent.java
- src/main/java/com/kdt/dto/RealEstateAgentDTO.java
- src/main/java/com/kdt/services/AgentService.java
> 공인중개사 테이블 변경

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/controllers/ReplyController.java
- src/main/java/com/kdt/repositories/BoardRepository.java
> NG-109 n+1 

- src/main/java/com/kdt/controllers/EstateAgentController.java
- src/main/java/com/kdt/dto/UpdateEstateDTO.java
- src/main/java/com/kdt/services/AgentService.java
공인중개사 회원정보 수정 기능 완료했습니다.
마이페이지 ui 일부 수정했습니다.
> NG-119 estate Info update

- src/main/java/com/kdt/controllers/EstateController.java
- src/main/java/com/kdt/repositories/EstateRepository.java
- src/main/java/com/kdt/services/EstateService.java
> 매물 정보 자신의 매물만 출력 되게

- src/main/java/com/kdt/controllers/ReviewApprovalController.java
- src/main/java/com/kdt/domain/entities/ReviewApproval.java
- src/main/java/com/kdt/dto/ReviewApprovalDTO.java
- src/main/java/com/kdt/mappers/ReviewApprovalMapper.java
- src/main/java/com/kdt/repositories/ReviewApprovalRepository.java
- src/main/java/com/kdt/services/ReviewApprovalService.java
> NG-120 myreview read

- src/main/java/com/kdt/controllers/ReviewApprovalController.java
- src/main/java/com/kdt/services/EstateService.java
마이페이지에 내가 본 방에 대한 정보 띄우기 1차로 완성했습니다.
> NG-120 mypage estate read

- src/main/java/com/kdt/controllers/EstateController.java
- src/main/java/com/kdt/controllers/ReviewApprovalController.java
- src/main/java/com/kdt/domain/entities/ReviewApproval.java
- src/main/java/com/kdt/repositories/ReviewApprovalRepository.java
- src/main/java/com/kdt/repositories/UploadEstateRepository.java
- src/main/java/com/kdt/services/EstateService.java
- src/main/java/com/kdt/services/ReviewApprovalService.java
문의하기 버튼 클릭 이벤트 / 리뷰 권한 주는 페이지
에 관한 컨트롤러와 서비스 코드 추가
> 문의하기 버튼 클릭 이벤트 / 리뷰 권한 주는 페이지

- src/main/java/com/kdt/config/WebConfig.java
- src/main/java/com/kdt/controllers/FilesController.java
- src/main/java/com/kdt/controllers/ReviewController.java
- src/main/java/com/kdt/domain/entities/Review.java
- src/main/java/com/kdt/domain/entities/ReviewFiles.java
- src/main/java/com/kdt/dto/ReviewDTO.java
- src/main/java/com/kdt/dto/ReviewFilesDTO.java
- src/main/java/com/kdt/dto/UploadReviewDTO.java
- src/main/java/com/kdt/mappers/ReplyMapper.java
- src/main/java/com/kdt/mappers/ReviewMapper.java
- src/main/java/com/kdt/repositories/ReviewRepository.java
- src/main/java/com/kdt/services/ReviewService.java
> NG-125 리뷰 작성 / 삭제 / 목록띄우기

- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/domain/entities/MapSubway.java
- src/main/java/com/kdt/mappers/MapSubwayMapper.java
- src/main/java/com/kdt/repositories/MapSubwayRepository.java
- src/main/java/com/kdt/services/MapService.java
> subway add

- src/main/java/com/kdt/controllers/EstateAgentController.java
- src/main/java/com/kdt/controllers/ReviewApprovalController.java
- src/main/java/com/kdt/domain/entities/SawEstate.java
- src/main/java/com/kdt/dto/SawEstateDTO.java
- src/main/java/com/kdt/mappers/SawEstateMapper.java
- src/main/java/com/kdt/repositories/SawEstateRepository.java
- src/main/java/com/kdt/services/ReviewApprovalService.java
마이페이지에 내가 본 방 띄우고, 권한에 따라 리뷰 쓰기 버튼 추가했습니다.
> NG-120 mypage saqEstate update

- src/main/java/com/kdt/controllers/ReviewController.java
- src/main/java/com/kdt/dto/UploadReviewDTO.java
- src/main/java/com/kdt/mappers/ReviewMapper.java
- src/main/java/com/kdt/repositories/ReviewFilesRepository.java
- src/main/java/com/kdt/repositories/ReviewRepository.java
- src/main/java/com/kdt/services/ReviewService.java
> NG-126 리뷰 수정 기능

- src/main/java/com/kdt/controllers/EstateAgentController.java
- src/main/java/com/kdt/dto/UpdateEstateDTO.java
- src/main/java/com/kdt/services/AgentService.java
로그인 엔터기능 추가 했습니다.
공인중개사 회원정보 수정기능에 위도 경도 기능 추가했습니다.
> NG-119 estate myInfo update

- src/main/java/com/kdt/controllers/ReviewApprovalController.java
- src/main/java/com/kdt/repositories/ReviewApprovalRepository.java
- src/main/java/com/kdt/services/ReviewApprovalService.java
> NG-131 관리자 리뷰 권한 추가

- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/domain/entities/MapSchool.java
- src/main/java/com/kdt/mappers/MapSchoolMapper.java
- src/main/java/com/kdt/repositories/MapSchoolRepository.java
- src/main/java/com/kdt/services/MapService.java
필터 업데이트 했습니다.
기본 디자인 틀 추가 했고
월세 드레그 바에 따라서 가격 조정되게 바꿨습니다.
> map filter update

- src/main/java/com/kdt/domain/entities/SawEstate.java
- src/main/java/com/kdt/dto/SawEstateDTO.java
- src/main/java/com/kdt/repositories/SawEstateRepository.java
- src/main/java/com/kdt/services/ReviewService.java
- 마이페이지에서 리뷰 작성 창으로 이동할 수 있도록 연결
> NG-132 마이페이지와 리뷰작성 연결

- src/main/java/com/kdt/controllers/ReviewApprovalController.java
- src/main/java/com/kdt/repositories/SawEstateRepository.java
- src/main/java/com/kdt/services/ReviewApprovalService.java
> NG-120 mypage sawEstate fixed

- src/main/java/com/kdt/controllers/ReviewApprovalController.java
- src/main/java/com/kdt/services/ReviewApprovalService.java
> NG-131 리뷰관리 수정

- src/main/java/com/kdt/config/MailConfig.java
- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/services/EstateService.java
- src/main/resources/application.properties
mapcontroller와 estate service에 매물 불러오기 기능을 추가했습니다.
> 최근 매물 불러오기 추가

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/repositories/BoardRepository.java
- src/main/java/com/kdt/services/BoardService.java
게시글을 내림차순으로 상위 6개만 불러오는 repository와 controller service를 수정했습니다.
> 게시글 목록 불러오기 수정

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/repositories/BoardRepository.java
- src/main/java/com/kdt/services/BoardService.java
id가 있을 때 게시글 목록이 6개 이상으로 출력되는걸 수정했습니다
> board service and repository 수정

- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/repositories/BoardRepository.java
- src/main/java/com/kdt/repositories/EstateRepository.java
- src/main/java/com/kdt/services/EstateService.java
- src/main/resources/application.properties
최근 매물을 전부 불러오는 것에서 6개만 불러오도록 수정하였습니다.
> 최근 등록된 매물 수정

- src/main/java/com/kdt/repositories/AgentRepository.java
- src/main/java/com/kdt/repositories/ReviewRepository.java
- src/main/java/com/kdt/services/ReviewService.java
공인중개사 테이블에 매너온도 업데이트 되도록 기능 추가
> NG-140 매너온도 테이블에 넣기

- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/services/MapService.java
스프링 부트 지금 에이전트 가져오기 하려고 했는데
찬양이가 나중에 하래서 일단 뭐 딱히 없구요 주석 처리만 해서 보냅니다.
> 맵 스프링 업데이트

- src/main/java/com/kdt/config/SecurityConfig.java
- src/main/java/com/kdt/controllers/ReviewApprovalController.java
- src/main/java/com/kdt/domain/entities/Estate.java
- src/main/java/com/kdt/domain/entities/RealEstateAgent.java
- src/main/java/com/kdt/dto/EstateDTO.java
- src/main/java/com/kdt/mappers/AgentMapper.java
- src/main/java/com/kdt/repositories/AgentRepository.java
- src/main/java/com/kdt/security/SecurityUser.java
- src/main/java/com/kdt/services/AgentService.java
- src/main/java/com/kdt/services/EstateSecurityService.java
> Real_Estate_Agent entity 이름 수정

- src/main/java/com/kdt/config/MailConfig.java
- src/main/java/com/kdt/controllers/EstateAgentController.java
- src/main/java/com/kdt/controllers/MemberController.java
- src/main/java/com/kdt/repositories/AgentRepository.java
- src/main/java/com/kdt/services/AgentService.java
- src/main/java/com/kdt/services/EstateService.java
- src/main/java/com/kdt/services/MemberService.java
> 중개사 아이디 찾기 추가

- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/repositories/AgentRepository.java
- src/main/java/com/kdt/services/MapService.java
매너 온도 가져올 수 있게 맵 컨트롤러와 관련 서비스 등등 수정 했습니다.
> map list update and fix

- src/main/java/com/kdt/repositories/ReviewRepository.java
- src/main/java/com/kdt/services/ReviewService.java
> 매너온도 넣는 로직 변경

- src/main/java/com/kdt/controllers/MailController.java
- src/main/java/com/kdt/repositories/AgentRepository.java
- src/main/java/com/kdt/repositories/MemberRepository.java
- src/main/java/com/kdt/services/AgentService.java
> 중개사 비밀번호 기능 추가

- src/main/java/com/kdt/controllers/ReviewApprovalController.java
- src/main/java/com/kdt/repositories/ReviewApprovalRepository.java
- src/main/java/com/kdt/services/ReviewApprovalService.java
approvalCode 에 a5 추가해서 리뷰 한 번 쓰면 내가 쓴 리뷰로 가기 버튼 뜨도록 만들었습니다.
> mypage review update

- src/main/java/com/kdt/services/ReviewService.java
> 매너온도 수정 로직 수정

- src/main/java/com/kdt/controllers/ReportController.java
- src/main/java/com/kdt/domain/entities/Report.java
- src/main/java/com/kdt/domain/entities/ReportContents.java
- src/main/java/com/kdt/domain/entities/ReportStatus.java
- src/main/java/com/kdt/dto/ReportContentsDTO.java
- src/main/java/com/kdt/dto/ReportDTO.java
- src/main/java/com/kdt/dto/ReportStatusDTO.java
- src/main/java/com/kdt/mappers/ReportContentsMapper.java
- src/main/java/com/kdt/mappers/ReportMapper.java
- src/main/java/com/kdt/mappers/ReportStatusMapper.java
- src/main/java/com/kdt/repositories/ReportRepository.java
- src/main/java/com/kdt/services/ReportService.java
> NG-141 신고관리 추가

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/domain/entities/RealEstateViews.java
- src/main/java/com/kdt/dto/RealEstateViewsDTO.java
- src/main/java/com/kdt/dto/ReportDTO.java
- src/main/java/com/kdt/mappers/RealEstateViewsMapper.java
- src/main/java/com/kdt/repositories/EstateRepository.java
- src/main/java/com/kdt/repositories/RealEstateViewsRepository.java
- src/main/java/com/kdt/repositories/ReportRepository.java
- src/main/java/com/kdt/services/EstateService.java
- src/main/java/com/kdt/services/NewEstateService.java
- src/main/java/com/kdt/services/NewMemberService.java
- src/main/java/com/kdt/services/RealEstateViewsService.java
- src/main/java/com/kdt/services/ReportService.java
- src/main/java/com/kdt/services/VisitorService.java
Estate관련은 매물 통계를 냈고 관리자 대시보드 관련 싹다 수정했습니다.
> NG-53 관리자 대시보드 수정

- src/main/java/com/kdt/controllers/ReportController.java
- src/main/java/com/kdt/domain/entities/MyReport.java
- src/main/java/com/kdt/dto/MyReportDTO.java
- src/main/java/com/kdt/mappers/MyReportMapper.java
- src/main/java/com/kdt/repositories/MyReportRepository.java
- src/main/java/com/kdt/services/ReportService.java
- src/main/java/com/kdt/services/ReviewApprovalService.java
> myReport create

- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/repositories/EstateImageRepository.java
- src/main/java/com/kdt/services/EstateService.java
클라이언트로부터 parent_id를 받아 db에 해당 id가 가지고있는 이미지 하나를 되돌려주는 로직을 추가했습니다.
> 최근 본 매물 이미지 불러오기

- src/main/java/com/kdt/controllers/FilesController.java
- src/main/java/com/kdt/domain/entities/Review.java
- src/main/java/com/kdt/dto/ReviewDTO.java
- src/main/java/com/kdt/dto/UploadReviewDTO.java
리뷰 익명/실명 여부 추가( DTO, Entity 수정했음 )
> NG-142 리뷰 익명/실명 여부 추가

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/controllers/EstateController.java
- src/main/java/com/kdt/controllers/VisitorController.java
- src/main/java/com/kdt/domain/entities/RealEstateViews.java
- src/main/java/com/kdt/domain/entities/Report.java
- src/main/java/com/kdt/dto/RealEstateViewsDTO.java
- src/main/java/com/kdt/repositories/RealEstateViewsRepository.java
- src/main/java/com/kdt/services/EstateService.java
- src/main/java/com/kdt/services/RealEstateViewsService.java
최근 5개 매물을 가져오기 위해 RealEstateViews관련해서 만들었고 Estate관련은 조회수 증가하기 위해 작성했습니다.
> 관리자 대시보드 수정

- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/services/MapService.java
> report and estate update

- src/main/java/com/kdt/config/WebConfig.java
- src/main/java/com/kdt/controllers/EstateAgentController.java
- src/main/java/com/kdt/domain/entities/AgentProfile.java
- src/main/java/com/kdt/dto/AgentProfileDTO.java
- src/main/java/com/kdt/mappers/AgentProfileMapper.java
- src/main/java/com/kdt/repositories/AgentProfileRepository.java
- src/main/java/com/kdt/services/AgentService.java
대표이미지와 관련된 엔티티,dto 기타 등등 생성
불러오기,저장과 관련된 코드 추가
대표 이미지는 한장만 저장되고 또 저장할 경우 이전에 잇던 것은 삭제하고 저장
불러오기 할때 만약의 경우를 대비해 List로 불러오지만 실제로는 하나의 dto만 반환할것으로 예상됨
> 공인중개사 대표 이미지 불러오기/저장

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/services/ReportService.java
> 관리자 쪽 수정했습니다.

- src/main/java/com/kdt/domain/entities/Member.java
- src/main/java/com/kdt/dto/MemberDTO.java
- src/main/java/com/kdt/services/MemberService.java
Member에 profile image 아무도 안써서 db에서 제거하고 entity와 dto 변경했습니다.
> Member's profile image delete

- src/main/java/com/kdt/domain/entities/ReviewApproval.java
- src/main/java/com/kdt/domain/entities/UploadReviewApproval.java
- src/main/java/com/kdt/dto/ReviewApprovalDTO.java
- src/main/java/com/kdt/dto/UploadReviewApprovalDTO.java
- src/main/java/com/kdt/services/ReviewApprovalService.java
전화번호 출력할 수 있도록 엔티티, dto 수정
전화번호 입력할 수 있도록 id로 member 검색하고 거기서 전화번호 꺼내서 전화번호 입력
> 문의자 전화번호 관련

- src/main/java/com/kdt/controllers/MapController.java
- src/main/java/com/kdt/domain/entities/MapRegion.java
- src/main/java/com/kdt/domain/entities/MapSchool.java
- src/main/java/com/kdt/domain/entities/MapSubway.java
DB이름 시작 문자 소문자에서 대문자로 바꿔서
엔티티 테이블 이름 수정 했습니다.
> DB Table Name Update

- src/main/java/com/kdt/controllers/ReviewController.java
- src/main/java/com/kdt/domain/entities/Review.java
- src/main/java/com/kdt/dto/ReviewDTO.java
- src/main/java/com/kdt/mappers/ReviewMapper.java
- src/main/java/com/kdt/repositories/ReviewRepository.java
- src/main/java/com/kdt/services/ReviewService.java
리뷰 게시판을 위해 리뷰 관련 디티오, 엔티티 등 수정
> NG-146 리뷰 게시판 

- src/main/java/com/kdt/domain/entities/MapRegion.java
- src/main/java/com/kdt/domain/entities/MapSchool.java
- src/main/java/com/kdt/domain/entities/MapSubway.java
- src/main/java/com/kdt/dto/MapRegionDTO.java
- src/main/java/com/kdt/dto/MapSchoolDTO.java
- src/main/java/com/kdt/dto/MapSubwayDTO.java
> map database update

- src/main/java/com/kdt/repositories/ReviewRepository.java
중개사무소 리뷰 모두 가져오기
중개사무소 번호로 가져오도록 수정
> 중개사무소 리뷰 모두 가져오기

- src/main/java/com/kdt/domain/entities/RealEstateAgent.java
- src/main/java/com/kdt/dto/RealEstateAgentDTO.java
- src/main/java/com/kdt/dto/UpdateEstateDTO.java
- src/main/java/com/kdt/services/AgentService.java
공인중개사 마이페이지에 공인중개사 소개글 추가했습니다.
> estate mypage content update

- src/main/java/com/kdt/controllers/MapController.java
> map logger add

- src/main/java/com/kdt/controllers/BoardController.java
- src/main/resources/application.properties
> 컨트롤러, 서비스 개발 단계에서 디버그 일단 적용

- src/main/java/com/kdt/controllers/AdminController.java
- src/main/java/com/kdt/controllers/Enrollmentcontroller.java
- src/main/java/com/kdt/controllers/ReportController.java
- src/main/java/com/kdt/controllers/VisitorController.java
Admin,Enrollment,Report,Visitor 컨트롤러들 추가 했습니다.
> logging 추가

- src/main/java/com/kdt/controllers/MailController.java
> sysout 지우기

- src/main/java/com/kdt/controllers/HomeController.java
- src/main/java/com/kdt/filters/RoutingFilter.java
- src/main/resources/application.properties
> RoutingFilter 적용

- src/main/java/com/kdt/controllers/FilesController.java
- src/main/java/com/kdt/services/BoardService.java
- src/main/java/com/kdt/services/ReviewService.java
> 파일 저장 경로 수정

- src/main/java/com/kdt/domain/entities/RealEstateAgent.java
- src/main/java/com/kdt/dto/RealEstateAgentDTO.java
dto,entity report_Count, signupDate 추가했습니다.
> RealEstateAgent 수정

- .gitignore
- src/main/java/com/kdt/controllers/BoardController.java
이제 application.properties는 수정 필요 없어서 gitignore에 추가합니다
> 충돌 방지를 위해 application.properties gitignore 추가

- .gitignore
- src/main/java/com/kdt/dto/RealEstateAgentDTO.java
- src/main/java/com/kdt/services/AgentService.java
- src/main/java/com/kdt/services/ReviewService.java
- src/main/resources/application.properties
application.properties 진짜 마지막 수정
생성자때문에 오류나서 일차적으로 막아놓음
> application.properties 진짜 마지막 수정

- src/main/java/com/kdt/services/AgentService.java
- src/main/java/com/kdt/services/EstateService.java
공인중개사 프로필 이미지, 매물 사진 파일 코드 수정했습니다.
각 파일이 들어갈 폴더명도 추가하였는데 이 부분은 제대로 동작할 지 잘 모르겠습니다.
폴더명은 agentProfiles, estateImages로 하였습니다
> file input

- src/main/java/com/kdt/config/SecurityConfig.java
- src/main/java/com/kdt/controllers/BoardController.java
- src/main/java/com/kdt/controllers/ReviewController.java
> 시큐리티 게시판, 리뷰 추가

- src/main/java/com/kdt/services/AgentService.java
- src/main/java/com/kdt/services/EstateService.java
sysName만 DB에 저장하고 링크가 필요하면 리액트에서 작성하도록 수정
> 파일 입력 방식 수정

- src/main/java/com/kdt/config/WebConfig.java
- src/main/java/com/kdt/repositories/ReviewRepository.java
- src/main/java/com/kdt/services/ReviewService.java
> 매너온도 수정, 웹 컨피크 변경

- src/main/java/com/kdt/services/AgentService.java
- src/main/java/com/kdt/services/EstateService.java
daebbang_storage -> daebbang
그리고 파일 삭제하는 코드 지우다가 DB에서 삭제하는 코드도 지워버렸길래 복구
> 이미지 넣는 링크 수정

- src/main/java/com/kdt/domain/entities/ReportStatus.java
- src/main/java/com/kdt/services/MapService.java
- src/main/resources/application.properties
> 바뀐 엔티티에 맞게 신고 변경

- src/main/java/com/kdt/repositories/AgentRepository.java
- src/main/java/com/kdt/services/ReviewService.java
> 신고횟수에 따라 매너온도 반영되게 만들었음

- src/main/java/com/kdt/services/EstateService.java
- src/main/resources/application.properties
logger 때문에 오류가 생겨서 삭제했습니다
properties에 naverid pw 는 의미가 없어서 삭제했습니다
> estate service logger 삭제
